Nordix/metal3-dev-tools

README.md, container/Dockerfile, container/run-workspace.sh, tools/init-repo.sh, tools/run-capb-tests.sh, tools/update-nordix-repos-master.sh
Adding:
- repo management scripts : init and update
- test script for baremetal provider
- Dockerfile and script to run a development container
=> Adding tools for development

ci/jobs/capi_bm_integration_tests.pipeline
Jenkins jobs require pipeline scripts to be in place. This is a dummy pipeline script just to make Jenkins job happy. We will build upon this to create a proper pipeline.
=> Dummy jenkins pipeline for capi bmo integration tests

README.md, getting-started.md, wow/github-workflow.md
Adding a getting-started that should contain all practical infos related to Nordix and airship.
=> Adding a getting-started

Makefile, README.md, configs/linter/.mdstylerc.rb, getting-started.md, resources/docker/linter/Dockerfile, wow/github-workflow.md
Add support to lint markdown files.
Fix markdown errors in md files.
closes #12
=> Add markdown lint

ci/scripts/openstack/README.md, ci/scripts/openstack/infra_defines.sh, ci/scripts/openstack/infra_delete_ci.sh, ci/scripts/openstack/infra_delete_dev.sh, ci/scripts/openstack/infra_setup_ci.sh, ci/scripts/openstack/infra_setup_dev.sh, ci/scripts/openstack/utils.sh
This PR contains OpenStack utility functions primarily required for CI and Dev infrastructure. In the start, only router and network setup/deletion is done.
=> Openstack Infra utility functions

ci/images/gen_base_ubuntu_image.sh, ci/images/image_builder_template.json, ci/images/userdata.tpl, ci/scripts/openstack/infra_defines.sh, ci/scripts/openstack/utils.sh, ci/scripts/provision_base_image.sh, ci/scripts/setup_chrony_ubuntu.sh, ci/scripts/setup_qemu_ubuntu.sh
Wireframe for image building scripts.
=> ci: Wireframe for image building scripts

ci/images/gen_metal3_ubuntu_image.sh, ci/scripts/provision_metal3_image.sh
Clones the metal3-dev-env repo and execute the
01_install_requirements.sh script
=> Add provisioning script for Metal3-dev-env image

Makefile, resources/docker/builder/Dockerfile
Contains:
- packer
- python 3.7
- Openstack client
- jq
=> Add a Dockerfile for image building container

ci/scripts/provision_base_image.sh, ci/scripts/provision_jumphost_jenkins_base_img.sh, ci/scripts/provision_metal3_image.sh
Adds provisioning script for Jenkins and Jumphost
Image.
=> ci: Add provisioning script for jenkins image

Makefile, README.md, ci/scripts/openstack/README.md, scripts/shell-linter.sh
=> Add shell linter

ci/images/gen_jumphost_jenkins_ubuntu_image.sh, ci/images/userdata.tpl, ci/scripts/artifactory/utils.sh, ci/scripts/jumphost/_add_proxy_user.sh, ci/scripts/jumphost/add_jumphost_user.sh, ci/scripts/jumphost/create_or_update_dev_jumphost.sh, ci/scripts/jumphost/del_jumphost_user.sh, ci/scripts/jumphost/update_dev_jumphost_users.sh, ci/scripts/jumphost/utils.sh, ci/scripts/openstack/infra_defines.sh, ci/scripts/openstack/utils.sh, ci/scripts/provision_base_image.sh, ci/scripts/provision_jumphost_jenkins_base_img.sh
Lifecycle scripts for Dev jumphost.
=> ci: jumphost lifecycle scripts

ci/scripts/artifactory/utils.sh, ci/scripts/jumphost/_add_proxy_user.sh, ci/scripts/jumphost/add_jumphost_user.sh, ci/scripts/jumphost/add_new_user_key.sh, ci/scripts/jumphost/create_or_update_dev_jumphost.sh, ci/scripts/jumphost/del_jumphost_user.sh, ci/scripts/jumphost/del_user_key.sh, ci/scripts/jumphost/update_dev_jumphost_users.sh, ci/scripts/jumphost/utils.sh
Scripts for adding and removing user ssh keys
from artifactory.
- added usage comments in different scripts
=> ci: Add/Del jumphost SSH keys

ci/scripts/image_scripts/provision_base_image.sh
ci: Install make in base images
=> ci: Install make in base images

ci/scripts/tests/files/run_integration_tests.sh, ci/scripts/tests/integration_delete.sh, ci/scripts/tests/integration_test.sh
=> Add scripts to create test executers and run tests

ci/jobs/linter_tests.pipeline
ci: add linter jobs pipeline script
=> ci: add linter jobs pipeline script

ci/jobs/capi_bm_integration_tests.pipeline, ci/jobs/linter_tests.pipeline
ci: Add agent to pipeline jobs
=> ci: Add agent to pipeline jobs

ci/scripts/image_scripts/provision_base_image.sh, ci/scripts/image_scripts/provision_jumphost_jenkins_base_img.sh, ci/scripts/jumphost/create_or_update_dev_jumphost.sh, ci/scripts/tests/integration_test.sh
Reduce size of the jumphost
disable unattended upgrades to fix apt issue
fix variable name issue in integration test scripts
=> Modify CI setup

wow/citycloud.md
For SSH config example mainly and guidelines on VM creation
=> Add a citycloud WoW guide

tools/setup_machines/README.md
Update Readme with Testcase information
Co-authored-by: Anwar Hassen anwar.hassen@est.tech
=> Kinder based test environment for k8s deployment

Makefile, README.md, scripts/files/ubuntu-metal3-config.yaml.tpl, scripts/run_metal3_vm.sh
The script creates a libvirt VM using the Openstack metal3 image
Co-authored-by: Nam Xuan Nguyen <nam.xuan.nguyen@est.tech>
=> Add a script to run a metal3 dev env locally from Openstack image

Makefile, ci/jobs/capi_bm_integration_tests.pipeline, ci/scripts/tests/files/run_integration_tests.sh, ci/scripts/tests/integration_delete.sh, ci/scripts/tests/integration_test.sh
TODO: Branches not supported, only master run so far
=> ci: add metal3 intergration test pipeline

README.md, ci/jobs/capi_bm_integration_tests.pipeline, ci/scripts/tests/integration_test.sh
fix issue with testing in upstream repos
=> Use the PR origin repo in integration tests

resources/docker/gotest/Dockerfile, resources/docker/gotest/run-test.sh
=> ci: gotest container spec for unit test

ci/jobs/capi_bm_integration_tests.pipeline, ci/jobs/capi_bm_units_tests.pipeline, ci/jobs/docker_image_building.pipeline, ci/jobs/linter_tests.pipeline
they are a bit arbitrary for now
=> Add timeouts in our jenkins jobs

ci/scripts/image_scripts/provision_metal3_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh
use make instead of 01_install_requirements.sh : https://github.com/metal3-io/metal3-dev-env/pull/56
=> Change call to metal3-dev-env script in CI image script

ci/jobs/update_nordix_repos.pipeline, scripts/update-nordix-repos-master.sh
automated update run by jenkins
included repos (to be updated on need basis):
- Nordix/cluster-api-provider-baremetal.git
- Nordix/cluster-api.git
- Nordix/baremetal-operator.git
- Nordix/metal3-docs.git
- Nordix/metal3-dev-env.git
=> ci: Update Nordix repositories to be syncronized with upstream

scripts/update-nordix-repos-master.sh
set default value for WORKSPACE
=> fix update Nordix repo script when running locally

ci/scripts/image_scripts/provision_jumphost_jenkins_base_img.sh, ci/scripts/image_scripts/provision_metal3_image.sh
With os cli update, no need to remove package in metal3 image
=> Update openstack cli in CI

ci/jobs/openstack_image_building.pipeline
hitting 30 mins with Ubuntu now
=> Increase openstack image building timeouts

ci/scripts/image_scripts/provision_metal3_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh
We are seeing some issues with the image size in the ci, this is to try to get more reliability
=> Do not bake in metal3 environment

ci/scripts/image_scripts/provision_node_image_centos.sh
Co-authored-by: Kanwar Saad <kanwar.saad.bin.liaqat@est.tech>
=> Remove old kernels to save disk space

scripts/update-nordix-repos-master.sh
-master branch is currently updated regularly
=> CI: add updating of Nordix v1alpha2 branch

ci/jobs/capi_bm_integration_tests.pipeline, ci/scripts/tests/files/run_integration_tests.sh, ci/scripts/tests/integration_test.sh
Use the CAPI_VERSION variable and only override the variables for the 
tested patchset
=> Modify the integration test env variables

ci/scripts/tests/files/run_integration_tests.sh
Run v1a1/v1a2 depending on the "CAPI_VERSION" environment variable
=> Add condition to run v1a1 & v1a2 test

ci/jobs/capi_bm_integration_tests.pipeline, ci/scripts/tests/files/run_integration_tests.sh, ci/scripts/tests/integration_test.sh
Export memory & distribution default variables for v1a2 integrations test.
=> Add v1a2 default environment variables.

ci/scripts/tests/files/run_integration_tests.sh
This PR corrects the name of memory size variable which is expected to be imported from integration_test.sh.
=> Correct variable name for node memory size.

ci/scripts/tests/files/run_integration_tests.sh
=> Run tests with images locally compiled

ci/jobs/capi_bm_integration_tests.pipeline
=> Increase timeout for e2e metal3 tests

ci/scripts/tests/files/run_integration_tests.sh
=> Do not run capbm locally, but use images built locally

ci/scripts/tests/files/run_integration_tests.sh
related to https://github.com/metal3-io/metal3-dev-env/pull/182
=> Add branch variable for e2e tests local images

ci/scripts/tests/files/run_integration_tests.sh
Jenkins job and m3 dev env changes in separate commits
=> CI: add v1alpha3 integration test

tools/deterministic_admin-conf_generation/README.md
- Added a folder that was missing due to it being empty
- Also contains information on supported platforms
=> Added a folder that was missing due to it being empty

wow/jenkins_ci/README.md
Update CI doc based on [#58](https://github.com/metal3-io/project-infra/pull/58)
=> Update CI doc based on #58

scripts/update-nordix-repos-master.sh
Keep Nordix metal3-io.github.io and project-infra repos in sync with upstream.
=> Keep repos in sync with upstream

scripts/init-repo.sh
Add cap-m3 repo in initialization script
=> Add cap-m3 repo in init script

scripts/update-nordix-repos-master.sh
Clone from `source ` branch of metal3-io.github.io
=> Clone from source branch for metal3-io.github.io

wow/jenkins_ci/README.md, wow/jenkins_ci/jenkins-check-ci.sh, wow/jenkins_ci/jenkins-jobs-to-scan.txt
string search patterns put to separate file
=> Enhance script for checking CI job status

tools/deterministic_admin-conf_generation/admin.sh
=> Replace openssl command with working version on suse

wow/jenkins_ci/README.md
Added instructions for how to run CI check script remotely
without a local repo and how to use customized string patterns.
=> README update

upgrade_tests/controlplane_upgrade/cp_osimage_K8S_upgrade.sh
=> CI test automation script for combined node image and k8s version 

upgrade_tests/common.sh, upgrade_tests/workers_upgrade/w_multi-worker-no-extra-node_ugprade.sh
Boot disk image upgrade for multi-worker cluster with no extra node.
=> Automated upgrade of multi-workers with no extra node

upgrade_tests/workers_upgrade/1m_3w_clusterupgrade.sh
- upgrade workers
- Scale in workers
- Upgrade CP
- Scale out worker
=> Node image upgrade steps 1 master and 3 workers:

upgrade_tests/common.sh, upgrade_tests/controlplane_upgrade/cp_multi-master-extra-node_ugprade.sh
Multi master part of scripts are separate
from single master on purpose.
=> CI test automation script cp_multi-master-extra-node_ugprade.sh

upgrade_tests/common.sh, upgrade_tests/controlplane_upgrade/cp_multi-master-one-worker_ugprade.sh
k8s version and node image upgrade steps 3 masters and 1 worker:
-Enable workload on master
-Scale in worker
-Upgrade CP
-Scale out worker
=> CI test automation script cp_multi-master-one-worker_ugprade.sh

upgrade_tests/controlplane_upgrade/cp_multi-master-extra-node_os_ugprade.sh
Automated boot disk image upgrade of multiple controlplane nodes in a cluster
=> Automated boot disk image upgrade of multi-controlplane cluster

upgrade_tests/upgrade.clusters.sh
Performs upgrade of boot disk image of both controlplane and worker nodes.
=> Upgrade boot disk image of the cluster

upgrade_tests/common.sh, upgrade_tests/workers_upgrade/w_osimage_upgrade.sh
Automated test for OS image upgrade of a worker node.
=> Automated Boot disk Image upgrade of a worker

upgrade_tests/common.sh, upgrade_tests/controlplane_upgrade/3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh
3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh
=> fix: add workload deployment before upgrade for worker node

upgrade_tests/common.sh
=> Reduced set of upgrade tests for test fw use

upgrade_tests/workers_upgrade/1cp_1w_bootDiskImage_extraNode_upgrade.sh, upgrade_tests/workers_upgrade/1cp_1w_bootDiskImage_scaleOutWorkers_upgrade.sh, upgrade_tests/workers_upgrade/1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
image checksum, replicas env variables and cluster
deprovisioning added
=> Worker test script updates

upgrade_tests/common.sh, upgrade_tests/workers_upgrade/1cp_1w_bootDiskImage_scaleOutWorkers_upgrade.sh, upgrade_tests/workers_upgrade/1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
small bug fix and added "sudo" command in Upgraded files...
=> Add variable, small bug fix in common.sh and two other test cases.

upgrade_tests/1cp_1w_bootDiskImage_cluster_upgrade.sh
Fixes an infinite loop issue during upgrade test.
=> Fix loop issue

upgrade_tests/upgrade.sh
Adding KCP update test script to the list of controlplane upgrade tests
=> Add KCP test case to list of control plane test scripts

upgrade_tests/workers_upgrade/1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
Add necessary code to fix the loop issue and modify the code to complete the update test case.
=> Fix loop issue and update code for the priority use case.

upgrade_tests/1cp_1w_bootDiskImage_cluster_upgrade.sh, upgrade_tests/common.sh, upgrade_tests/controlplane_upgrade/1cp_0w_bootDiskImage_extraNode_upgrade.sh, upgrade_tests/controlplane_upgrade/1cp_0w_k8sVer_bootDiskImage_extraNode_upgrade.sh, upgrade_tests/controlplane_upgrade/1cp_0w_k8sVer_extraNode_upgrade.sh, upgrade_tests/controlplane_upgrade/1cp_1w_kubeadm_update.sh, upgrade_tests/controlplane_upgrade/3cp_0w_bootDiskImage_extraNode_upgrade.sh, upgrade_tests/controlplane_upgrade/3cp_0w_k8sVer_extraNode_upgrade.sh, upgrade_tests/controlplane_upgrade/3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh, upgrade_tests/upgrade.sh, upgrade_tests/workers_upgrade/1cp_1w_bootDiskImage_extraNode_upgrade.sh, upgrade_tests/workers_upgrade/1cp_1w_bootDiskImage_scaleOutWorkers_upgrade.sh, upgrade_tests/workers_upgrade/1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
-increased modularity
-majority of duplicate code removed
-minimum test set run successfully
3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh
1cp_1w_bootDiskImage_cluster_upgrade.sh
1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
=> Upgrade test script refactoring

ci/jobs/openstack_image_building.pipeline
Removes typo character in image_building_pipeline
=> Remove typo in image_building_pipeline

ci/images/gen_metal3_centos_volume.sh, ci/images/gen_metal3_ubuntu_volume.sh, ci/scripts/image_scripts/provision_metal3_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh
and do not include the metal3 deployment in the image
=> Use metal3 images to generate volumes for CI

ci/scripts/image_scripts/hardening_base_image.sh
since we do not use passwords in CI vms
=> Remove password policies

ci/scripts/image_scripts/provision_metal3_image_centos.sh
First try to fix [Jenkins /test-v1a3-centos-integration fail](https://jenkins.nordix.org/view/Airship/job/airship_metal3io_project_infra_v1a3_integration_test_centos/32/console) in [pull/126](https://github.com/metal3-io/project-infra/pull/126)
=> Fix centos error with minikube

ci/scripts/image_scripts/provision_metal3_image_centos.sh
Minikube veth interfaces are not deleted properly currently and this patch will try to fix the issue
=> Reworked minikube veth interface deletion

ci/images/gen_base_ubuntu_image.sh, ci/images/gen_metal3_ubuntu_image.sh, ci/images/gen_ubuntu_node_image.sh, ci/images/image_builder_template.json, ci/scripts/image_scripts/node-image-cloud-init/retrieve.configuration.files.sh, ci/scripts/image_scripts/provision_node_image.sh
This PR adds the node image building scripts with pre-baked packages
=> Add node image building scripts

ci/images/gen_base_ubuntu_image.sh, ci/images/gen_ubuntu_node_image.sh, ci/images/image_builder_template.json
This PR fixes the image flavor variable name mismatch
=> Fix image flavor variable naming

ci/scripts/image_scripts/hardening_base_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh
Removing test user which was added for debugging purposes and reverting everything back to its original state.
=> Remove test user and revert back

ci/images/gen_metal3_centos_image.sh, ci/scripts/artifactory/shrink_resize_upload_node_image.sh, ci/scripts/image_scripts/provision_node_image_centos.sh
This PR adds prebaked centos node image building scripts.
=> Add centos node image building scripts

wow/github-workflow.md
Add a guide on how to backport a commit from master to a stable branch.
=> Add a guide to backport a commit

ci/jobs/openstack_node_image_building.pipeline
=> Fix openstack node image building pipeline

ci/images/gen_metal3_centos_image.sh, ci/images/gen_node_ubuntu_image.sh, ci/jobs/openstack_node_image_building.pipeline
Node image uploading is not called at the right place. This PR fixes it.
=> Fix node image upload

ci/jobs/openstack_node_image_building.pipeline
{} was missing in node image building pipeline
=> Fix bug in node image building pipeline

wow/github-workflow.md
Update missing parts/commands in backporting instructions.
=> Update ##How to backport instructions

ci/scripts/image_scripts/provision_metal3_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh, ci/scripts/image_scripts/provision_node_image.sh, ci/scripts/image_scripts/provision_node_image_centos.sh, ci/scripts/image_scripts/source_cluster_container_images.sh, ci/scripts/image_scripts/target_cluster_container_images.sh
Prepull container images hosted in docker hub
Fixes: metal3-io/project-infra#166
=> Prepull container images hosted in docker hub

ci/scripts/image_scripts/source_cluster_container_images.sh, ci/scripts/image_scripts/target_cluster_container_images.sh
Start the CRI-O before pulling the images.
=> Start the CRI-O before pulling the images

ci/scripts/image_scripts/provision_metal3_image_centos.sh, ci/scripts/image_scripts/provision_node_image_centos.sh
=> Fix bin PATH for sudo

ci/images/gen_metal3_ubuntu_volume.sh, ci/scripts/image_scripts/source_cluster_container_images.sh
Make sure to copy image script
=> Make sure to copy image script

ci/scripts/image_scripts/target_cluster_container_images.sh
Upgrade calico images due to its new [release](https://github.com/projectcalico/calico/releases/tag/v3.17.2).
=> Upgrade calico images in due its new release

ci/scripts/image_scripts/target_cluster_container_images.sh
Move the Calico to [v3.17.3](https://github.com/projectcalico/calico/releases/tag/v3.17.3)
=> Move the Calico to v3.17.3

ci/scripts/image_scripts/target_cluster_container_images.sh
Upgrade calico images to 3.8.1
=> Upgrade calico images to 3.8.1

ci/scripts/image_scripts/install_crio_on_centos.sh, ci/scripts/image_scripts/install_crio_on_ubuntu.sh, renovate.json
This PR adds renovate.json configuration file to the repo, so Renovate can work with it.
=> Add renovate configuration file into this repo

Makefile, ci/jobs/update_nordix_artifacts.pipeline, scripts/update-nordix-artifacts.sh
Add a pipeline with a script for keeping choice artifacts up to date in Nordix Artifactory.
See the corresponding job creation in Gerrit: https://gerrit.nordix.org/c/infra/cicd/+/8455
=> Add a Jenkins pipeline for updating Nordix Artifacts

scripts/update-nordix-repos-master.sh
Repo has been archived: https://github.com/metal3-io/cluster-api-provider-baremetal
=> Remove archived CAPIPB repo from repo update job

ci/images/userdata.tpl
=> Revert changes on /etc/resolv.conf

capo/run-openstack-command.sh
To be used by developer and from other scripts
=> Add a script to run a one time openstack command.

capo/clean-os-resources.sh
Make OpenStack resources cleaning script interactive
=> Make OpenStack resources cleaning script interactive

ci/images/gen_metal3_centos_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh
=> Revert using CentOS Stream image

capo/clean-os-resources.sh
This PR improves the resource cleaning script:
- Reuses existing script to run openstack command
- Fixes errors caused by special characters returned by Openstack clients
- Frees unused floating IPs that were causing Quota issues when creating servers.
=> Improve resource cleaning script

capo/README.md
Add devstack installation instruction
=> Add devstack installation instruction

capo/Makefile, capo/clean-os-resources.sh, capo/configure.sh
=> Replace hardcoded values

ci/scripts/image_scripts/target_cluster_container_images.sh
Upgrade Calico images to v3.20.0
=> Upgrade Calico images

scripts/update-nordix-repos-master.sh
This PR adds IPA and IPA builder repositories in update repo script to keep the repos updated with upstream.
=> Add IPA repositories in update repo script

ci/scripts/image_scripts/install_crio_on_centos.sh, ci/scripts/image_scripts/install_crio_on_ubuntu.sh
Downgrade crictl to 1.21.2 since there is no Release Key for 1.22.0 yet
=> Downgrade crictl to 1.21.2

ci/scripts/image_scripts/install_crio_on_centos.sh, ci/scripts/image_scripts/install_crio_on_ubuntu.sh
There is no release 1.21.2 for cri tools
=> Downgrade crictl to 1.21.0

ci/scripts/image_scripts/start_centos_ipa_build.sh
Fix incorrect var in IPA building
=> Fix incorrect var in IPA building

ci/scripts/image_scripts/build_ipa.sh, ci/scripts/image_scripts/start_centos_ipa_ironic_build.sh
With this commit it will be possible to build IPA based on any
commit in the repository.
=> Fix incorrect IPA cloning process

ci/scripts/image_scripts/install_crio_on_centos.sh, ci/scripts/image_scripts/install_crio_on_ubuntu.sh, ci/scripts/image_scripts/source_cluster_container_images.sh
Switch kind version to 1.21.2 and crictl to 1.21.0
=> Switch kind version to 1.21.2 and crictl to 1.21.0

ci/scripts/image_scripts/run_build_ironic.sh, ci/scripts/image_scripts/start_centos_ipa_ironic_build.sh
This PR will add Ironic and Ironic-inspector vars in image building and export them to metadata file.
=> Add Ironic and Ironic-inspector vars in ironic image builiding process

ci/jobs/openstack_image_building.pipeline
Image building pipeline is not correctly working with wrong curly braces. Also post stage was placed wrongly in previous PR.
=> Fix Image building pipeline

ci/jobs/artifactory_cleanup.pipeline
The script was not working correctly inside a container but it works
fine without the container and there is no need for the container so
the container wrapper was removed.
=> Fix artifactory cleanup script

scripts/update-nordix-repos-master.sh
This commit also makes the sync script shellcheck compatible.
=> Add syncing for capm3 release branches

scripts/update-nordix-repos-master.sh
This PR also moves the custom repo update logic to a
function to provide reusable functionality.
This PR  unifies the indentation.
=> Implement syncing for IPAM release branches

scripts/update-nordix-repos-master.sh
Also removes hard coded references to master since the script is anyway
using the default branch no matter if it is main or master.
=> Add topolvm repo to sync script

ci/scripts/image_scripts/source_cluster_container_images.sh
=> uplift golang version to 1.17

renovate.json
Removes @jan-est @wgslr and adds @ren-yifei to the assignees' list in renovate.json
=> Update renovate assignees list

ci/scripts/image_scripts/install_crio_on_centos.sh, ci/scripts/image_scripts/install_crio_on_ubuntu.sh
cri-o 1.23.0 suffering from a bug https://github.com/cri-o/cri-o/pull/5539
=> Downgrade crictl to 1.22.0

README.md
Related to https://gerrit.nordix.org/c/infra/cicd/+/12263/1/jjb/metal3/job_metal3_dev_tools_integration_test_centos.yml & https://gerrit.nordix.org/c/infra/cicd/+/12263/1/jjb/metal3/job_metal3_dev_tools_integration_test_ubuntu.yml
=> 📖 Add metal3-dev-tools integration test how to use notes

ci/jobs/metal3_dev_tools_integration_tests.pipeline
This PR fixes IMAGE_OS name in condition in metal3_dev_tools_integration_tests.pipeline
=> Fix IMAGE_OS name in condition in metal3 dev tools integration

ci/jobs/artifact_cleanup.pipeline
This is renaming needed because this job is now contains harbor cleanup
not only artifactory cleanup.
=> rename the artifactory cleanup to artifact cleanup

scripts/update-nordix-repos-master.sh
It would be nice to have these also synced when working on backports and similar.
=> Sync CAPO release branches

capo/README.md, capo/capo_os_vars.rc, capo/clusterctl_template.sh, capo/configure.sh
- Bumped CAPI version
- Bumped kubernetes version
- Bumped yq version (v4 is now supported in CAPO)
- Updated docs and added cleanup instructions
=> Update CAPO docs and scripts

ci/scripts/image_scripts/setup_monitoring_centos.sh
This PR fix the sysstat metrics configuration and it will allow us to have the binary file for infrastructure metrics graph.
=> Fix metrics monitoring setup for Cetos

ci/images/centos_userdata.tpl, ci/images/gen_metal3_centos_image.sh, ci/scripts/image_scripts/provision_node_image_centos.sh
This commit also does additional changes to allow Centos Stream 9 to work properly.
=> Uplift to Centos Stream 9

ci/images/README.md, ci/images/run_local.sh, ci/scripts/image_scripts/provision_base_image.sh
Also adds documentation for how to upload, list and delete images at Artifactory.
=> Local image build: support ubuntu

scripts/update-nordix-repos-master.sh
sriov-cni and sriov-network-device-plugin repos are added to update-nordix-repos-master script.
=> Sync sriov-cni and sriov-network-device-plugin repos

scripts/update-nordix-repos-master.sh
This PR fixes the typo in the sriov repo name.
=> Minor fix for sriov repo name

ci/scripts/image_scripts/bmh-patch-long-serial.yaml, ci/scripts/image_scripts/bmh-patch-short-serial.yaml, ci/scripts/image_scripts/build_ipa.sh, ci/scripts/image_scripts/start_centos_ipa_ironic_build.sh
At this moment IPA's agressive serial search feature exists only on
the Nordix IPA fork but hopefully this feature will be implemented
upstream.
=> add support for IPA agressive serial search

ci/images/centos_userdata.tpl
It will help for debugging after crushes and reboots
=> ✨ Make journalctl persistent on centos

ci/images/centos_userdata.tpl
Reverts Nordix/metal3-dev-tools#608
=> Revert "🐛 Exclude NetworkManager upgrades"

ci/scripts/image_scripts/provision_node_image_centos.sh
related to https://github.com/metal3-io/metal3-dev-env/pull/1093
=> Downgrade to NetworkManager-1.40.0-1.el9

ci/jobs/openstack_image_building.pipeline
Doing this as a trial to solve issue in https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_openstack_image_building/435/execution/node/66/log/
=> CI: Use nested creds in image build pipeline

ci/images/README.md
Current image building process is rather complicated, document it via Mermaid flowchart in the ci/images/README.md.
=> readme: document image building

ci/scripts/image_scripts/provision_jumphost_jenkins_base_img.sh
This upgrades jdk version from version 8 to 11.
=> Update jdk to version 11 on jenkins jumphost

tools/ironic-python-agent-image/README.md, tools/ironic-python-agent-image/unpack-ipa-archive.sh
This script can unpack IPA archive and makes it trivial to compare it with another build.
=> tools: add script to unpack IPA archive

ci/images/image_builder_template.json, ci/images/image_builder_template_node.json, ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh, ci/scripts/image_scripts/provision_base_image.sh, ci/scripts/image_scripts/provision_jumphost_jenkins_base_img.sh, ci/scripts/image_scripts/provision_metal3_image_ubuntu.sh, ci/scripts/image_scripts/provision_node_image_ubuntu.sh
This commit adds retires to apt and packer commands involved in openstack,jumphost,base and node image building.
=> add retries to apt and packer

Makefile, scripts/go-linter.sh
Reverts Nordix/metal3-dev-tools#651
=> Revert "Test commit"

renovate.json
I no longer contribute to this project. As such, it makes sense to remove my name from the list.
/cc @kashifest
=> renovate: remove fmuyassarov from assignees

ci/scripts/image_scripts/source_cluster_container_images.sh
=> fix centos image registry url

ci/scripts/image_scripts/install_crio_on_ubuntu.sh, ci/scripts/image_scripts/provision_node_image_ubuntu.sh, ci/scripts/image_scripts/setup_docker_ubuntu.sh
=> Update setting OS repos and keys since depreciation of apt-key

scripts/update-nordix-repos-master.sh
Adds release-1.4 branch for downstream fork sync.
=> Add release-1.4 branch updates

ci/scripts/image_scripts/run_build_ironic.sh
ironic image patching removed.
=> ironic image patching removed

resources/docker/builder/Dockerfile
=> Add qemu-img package to image-builder container image

ci/scripts/image_scripts/upload_node_image_rt.sh
This PR adds a check where newly built node image is checked for corruptions by converting it to IMG disk image format before pushing it to artifactory
=> Verify node image is not corrupted

ci/scripts/image_scripts/backup_node_image.sh
On earlier merged PR( #679) I missed that images are build inside the container and removed with container. 
With this fix new image is downloaded  and pushed back to artifactory with new (backup) name.
=> Fix backup node image

scripts/update-nordix-repos-master.sh
Sync `release-1.5` branches from upstream to Nordix forks.
=> add release-1.5 branches to sync

renovate.json
fixes https://github.com/Nordix/metal3-dev-tools/issues/664
=> Add huutomerkki to assignees list and fix renovate config

scripts/build-container-image.sh, scripts/files/container_image_names.json
As titled. The script is meant to be run from a managed environment. It assumes necessary tools and credentials are in place.
=> Add script to build, push and cleanup container images

ci/images/gen_metal3_centos_image.sh, ci/images/gen_metal3_ubuntu_image.sh, ci/scripts/openstack/utils.sh
This PR adds workflow to backup metal3 images in Kna1 region.
=> Backup metal3 images

ci/images/gen_base_ubuntu_image.sh
This commit only does what the title say.
=> update ubuntu source image used for base image

scripts/update-nordix-repos-master.sh
Add release-0.3 and release-0.4 to sync.
=> add BMO release branches to sync

ci/jobs/container_image_building.pipeline
This takes into use the new quay credentials
=> Change the credentials use for quay in container image build pipeline

ci/jobs/container_image_building.pipeline
This variable was named 'ghprbTargetBranch', but has nothing to do with ghprb.
=> Rename variable for branch name in container-build pipeline

ci/scripts/image_scripts/provision_node_image_centos.sh, ci/scripts/image_scripts/provision_node_image_ubuntu.sh, ci/scripts/image_scripts/target_cluster_container_images.sh
Migrate to k8s community-owned repo as suggested by https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/.
=> Migrate to k8s community-owned repos.

resources/docker/builder/Dockerfile
And fix a typo (which passes for whatever reason) in the builder reference.
=> pin the main Python image as well

ci/images/gen_metal3_ubuntu_image.sh
1. do not recreate keypair each time, it is conflicting between jobs
2. check if network detection fails, and abort before trying to call packer build, which would explode with cryptic issues"
=> image building improvements

scripts/update-nordix-repos-master.sh
Also, fix the sorting and some shellcheck issues.
=> add community repo, and CAPI and CAPO new release branches for sync

scripts/update-nordix-repos-master.sh
Add release-23.1 release branch to be synced to Nordix.
=> add ironic-image release branches to be synced

scripts/update-nordix-repos-master.sh
=> Add release-1.6 branch updates for CAPM3 and IPAM and release-0.5 branch for BMO

scripts/update-nordix-repos-master.sh
Stop syncing the EOL release branches.
=> stop syncing EOL release branches to Nordix

scripts/update-nordix-repos-master.sh
Add new release branch for syncing.
=> add ironic-image release-24.0 to sync

scripts/update-nordix-repos-master.sh
Add ironic-image release-24.1 branch to sync.
=> add ironic-image 24.1 release branch to sync

scripts/update-nordix-repos-master.sh
Remove old branches too.
Supersedes: #760
=> Add support for release-1.7 syncing to Nordix

ci/jobs/artifact_cleanup.pipeline, ci/jobs/update_nordix_repos.pipeline
This PR moves artifact cleanup and Nordix repos sync job to dynamic workers.
=> Move Artifact cleanup and Nordix repos sync jobs to dynamic workers

ci/jobs/artifact_cleanup.pipeline, ci/jobs/update_nordix_repos.pipeline
This PR  moves artifact cleanup test to private cloud
=>  Move artifact cleanup test to private cloud

scripts/update-nordix-repos-master.sh
=> :seedling: Remove release 1.5

OWNERS_ALIASES
Remove mboukhalfa from approvers in Nordix repos.
=> remove mboukhalfa from approvers

scripts/update-nordix-repos-master.sh
Add 1.9/0.9 release series branches to sync.
Remove old, unmaintained branches from all of them.
=> update branches to sync

scripts/update-nordix-repos-master.sh
Update release branches to be synced for IPAM, CAPM3, BMO, CAPI, CAPO, and Ironic-image.
=> update release branches to be synced

OWNERS_ALIASES
Add Peppi-Lotta and Feruz as approvers.
=> add Peppi-Lotta and Feruz as approvers

scripts/update-nordix-repos-master.sh
Add ironic-image release-31.0 to Nordix sync.
=> add ironic-image release-31.0 to nordix sync

scripts/update-nordix-repos-master.sh
Update branches we sync to Nordix for CAPI and CAPO.
=> update CAPI and CAPO synced branches

scripts/update-nordix-repos-master.sh
Add CAPO 0.13 branch to be synced to Nordix.
=> add CAPO 0.13 to be synced
