Nordix/metal3-dev-tools

.gitignore, README.md, container/Dockerfile, container/run-workspace.sh, tools/init-repo.sh, tools/run-capb-tests.sh, tools/update-nordix-repos-master.sh
Move repos around to be correctly located in the go path, install Bazel and change the gitignore to ignore the other repositories and go path
=> Reorganize container go tree

ci/jobs/linter_tests.pipeline
Absolute paths needed for linter make variables
=> Fix absolute paths for linter repos

ci/jobs/update_nordix_repos.pipeline
The actual credential is https://jenkins.nordix.org/credentials/store/system/domain/_/credential/nordix-airship-github-ssh/update
The error was https://jenkins.nordix.org/view/Airship/job/airship_update_nordix_repos/161/console
=> Fix credentials ID for nordix update job

ci/jobs/capi_bm_integration_tests.pipeline
This patch will force to kill ci job if there is an error&timeout during integration test.
=> Kill ci job if integration test faces an error

ci/jobs/capi_bm_integration_tests.pipeline
This patch tracks time of a single pipeline stage in order to kill the integration job if timeout happens during the test.
=> Add timestamp to catch timeout error on metal3-dev-env integration test

ci/images/README.md, ci/images/gen_metal3_centos_image.sh, ci/jobs/openstack_image_building.pipeline, ci/scripts/image_scripts/provision_node_image_centos.sh, ci/scripts/openstack/infra_defines.sh
Pre-bake centos master and worker images to be ready for booting.
Faster startup since init and join can be run immediately.
=> ci: generate centos images

ci/jobs/openstack_image_building.pipeline
-the image size turned out to be too large
-optimization efforts did not reduce the image size enough
=> CI: Remove generation of Metal3 CentOS node image

ci/jobs/docker_image_building.pipeline, resources/docker/gotest/Dockerfile
This PR 
- fixes curling the latest binary of kustomize
- adds missing go-unittest container to docker image building CI
=> Fix curling the latest binary of kustomize

scripts/update-nordix-repos-master.sh
capbm v1aplha2 branch was merged to master in upstream
so this sync from upstream to Nordix became obsolete
An example was created on purpose for future needs.
=> capbm v1aplha2 sync removed

ci/scripts/image_scripts/provision_metal3_image.sh
Missing sudo causes the image building to fail
=> Add sudo in image building for metal3

tools/deterministic_admin-conf_generation/README.md, tools/deterministic_admin-conf_generation/admin.sh
This script generates _admin.conf for accessing a kubernetes cluster.
Takes the following two optional and one mandatory inputs. 
optional: ca.crt and ca.key
mandatory: endpoint
=> Generate admin.conf before the cluster is created.

upgrade_tests/controlplane_upgrade/1cp_1w_kubeadm_update.sh, upgrade_tests/upgrade.sh
**What this PR does / why we need it:**
This PR adds automation test script for when KubeadmConfig commands need to be changed / users should be able to update KubeadmConfig commands during the upgrade, this PR is needed to automate manual testing of the upgrade process of kcp.
=> CI test automation script for KubeadmConfig commands to be mutated

upgrade_tests/1cp_1w_bootDiskImage_cluster_upgrade.sh
Image Checksum is added to control plane and worker node image in 1cp_1w_bootDiskImage_cluster_upgrade.sh file.
=> Add Image checksum for new upgrade image

upgrade_tests/1cp_1w_bootDiskImage_cluster_upgrade.sh, upgrade_tests/common.sh, upgrade_tests/workers_upgrade/1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
If a test script fails due to timeout,
deprovision cluster and continue to the next test.
=> Upgrade test failure handling improved

upgrade_tests/common.sh
wait_for_ctrlplane_provisioning_start might finish too early
when more than one machine being provisioned.
=> Upgrade common fix

upgrade_tests/1cp_1w_bootDiskImage_cluster_upgrade.sh, upgrade_tests/common.sh, upgrade_tests/controlplane_upgrade/1cp_0w_bootDiskImage_extraNode_upgrade.sh, upgrade_tests/controlplane_upgrade/1cp_0w_k8sVer_bootDiskImage_extraNode_upgrade.sh, upgrade_tests/controlplane_upgrade/1cp_0w_k8sVer_extraNode_upgrade.sh, upgrade_tests/controlplane_upgrade/1cp_1w_kubeadm_update.sh, upgrade_tests/controlplane_upgrade/3cp_0w_bootDiskImage_extraNode_upgrade.sh, upgrade_tests/controlplane_upgrade/3cp_0w_k8sVer_extraNode_upgrade.sh, upgrade_tests/controlplane_upgrade/3cp_1w_k8sVer_bootDiskImage_scaleInWorker_upgrade.sh, upgrade_tests/upgrade.sh, upgrade_tests/workers_upgrade/1cp_1w_bootDiskImage_extraNode_upgrade.sh, upgrade_tests/workers_upgrade/1cp_1w_bootDiskImage_scaleOutWorkers_upgrade.sh, upgrade_tests/workers_upgrade/1cp_3w_bootDiskImage_scaleInWorkers_upgrade_both.sh
-upgrade.sh script calls changed from './' to
'source' which impacted the logging prefix.
-small fixes to cluster deprovisioning and
control plane ip discovery after an upgrade
=> Upgrade test script updates

ci/scripts/image_scripts/provision_metal3_image_centos.sh
Possible fix for below pasted minikube stop error from CI. As it seen below, minikube will be stopped already, but with this patch we try to delete minikube following the same format as minikube stop:
```
`+ sudo su -l -c 'minikube stop' ****
* Stopping "minikube" in kvm2 ...
* Node "minikube" stopped.
++ sudo virsh domiflist minikube
+ MINIKUBE_IFACES='Interface  Type       Source     Model       MAC
-------------------------------------------------------
-          network    default    virtio      c0:d4:fe:03:b3:27
-          network    minikube-net virtio      94:51:0f:21:1b:26'
+ echo 'Interface  Type       Source     Model       MAC
-------------------------------------------------------
-          network    default    virtio      c0:d4:fe:03:b3:27
-          network …
```
=> Fix for minikube delete command

ci/jobs/openstack_image_building.pipeline
This PR removes volume building for Centos and leaves building Ubuntu for now, until maybe we find a way out to solve an issue with building Centos volumes.
=> Remove centos volume building from CI

ci/images/gen_ubuntu_node_image.sh, ci/scripts/artifactory/shrink_resize_upload_node_image.sh
This PR adds functionality to download a node image from openstack, performs shrink,resize operations on the image and upload node image to artifactory using a script.
=> Add script to shrink,resize and upload node image

ci/images/gen_metal3_centos_volume.sh, ci/images/gen_metal3_ubuntu_volume.sh
When creating a volume, volume might go into error status and stay there due to the improper condition check. This PR fixes that, by checking if volume status contains the substring error.
=> Fix condition checking when volume status contains an error substring

resources/docker/linter/Dockerfile
The current image being old is suffering from errors like 
```
Error installing mdl:
The last version of chef-utils (>= 0) to support your Ruby & RubyGems was 16.6.14. Try installing it with `gem install chef-utils -v 16.6.14` and then running the current command again
chef-utils requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
```
This PR fixes the issue.
=> Fix lint image Dockerfile

ci/jobs/openstack_node_image_building.pipeline, ci/scripts/image_scripts/upload_node_image_rt.sh
This PR exports artifactory credentials correctly in node image pipeline.
=> Export artifactory credentials correctly in node image pipeline

ci/scripts/image_scripts/setup_docker_ubuntu.sh
With newest docker verion i.e. 20.10 kubeadm init is failing for node
images
=> Fix docker version to 1.19.3 Ubuntu

ci/scripts/image_scripts/provision_node_image.sh
Docker installation 19.03.14 is not working properly. This commit tries
to do few tricks to test it.
=> Fix docker installation in Ubuntu Node image

ci/images/image_builder_template.json, ci/scripts/image_scripts/provision_node_image.sh
1. There is no volume build in normal openstack image building, so
volume size is unnecessary
2. We do not need to hold kubelet,kubeadm,kubectl. That was an
experimental code.
=> Remove unnecessary code pieces

ci/images/gen_metal3_centos_image.sh, ci/images/gen_node_ubuntu_image.sh, ci/scripts/image_scripts/install_crio_on_centos.sh, ci/scripts/image_scripts/install_crio_on_ubuntu.sh, ci/scripts/image_scripts/provision_node_image.sh, ci/scripts/image_scripts/provision_node_image_centos.sh, ci/scripts/image_scripts/upload_node_image_rt.sh
Install k8s 1.20 binaries on the target node image. Use CRI-O as container runtime for kubelet instead of Docker.
=> WIP: Use Kubernetes latest release 1.20

ci/scripts/image_scripts/target_cluster_container_images.sh
Fix calico image var
```
Type     Reason            Age                  From               Message
----     ------            ----                 ----               -------
Warning  FailedScheduling  12m (x3 over 12m)    default-scheduler  0/2 nodes are available: 2 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
Normal   Scheduled         12m                  default-scheduler  Successfully assigned kube-system/calico-kube-controllers-744cfdf676-97mk9 to test1-54fcf5dd94-kwhd4
Normal   Pulling           9m16s (x4 over 12m)  kubelet            Pulling image "docker.io/calico/kube-controllers:v3.17.1"
Warning  Failed            8m42s (x4 over 11m)  kubelet            Failed to pull image "docker.io/calico/kube-controllers:v3.17.1": rpc error: code = …
```
=> Fix calico image var

ci/scripts/image_scripts/source_cluster_container_images.sh
Bump the Golang version to [1.16](https://blog.golang.org/go1.16). This is needed to make sure that we download the right version of the Golang container images that will be used in BMO/CAPM3/IPAM repos while building the controller images. This PR should be the last one to merged after.
=> Bump the Golang version to 1.16

ci/scripts/image_scripts/target_cluster_container_images.sh
Upgrade calico images to [v3.18.0](https://github.com/projectcalico/calico/releases/tag/v3.18.0)
=> Upgrade calico images

ci/scripts/image_scripts/source_cluster_container_images.sh
Kind node image version isn't 1:1 with Kubernetes version. The latest version is v1.20.2.
=> Fix the kind image var

resources/docker/builder/Dockerfile
This fixes an issue where the Python cryptography package would not
build when running `make build-image-builder. The Rust compiler has been
added as a dependency for building this Python package.
See: https://github.com/pyca/cryptography/issues/5771
=> Add cargo dependency to image-builder Dockerfile

ci/scripts/image_scripts/provision_node_image.sh, ci/scripts/image_scripts/provision_node_image_centos.sh
I've pushed a patched version of kubeadm v1.20.4 which waits 30 seconds before trying to start etcd to Artifactory. There's no telling how long this bug is going to be around in Kubernetes, so I've amended the image build shell scripts so that we can use our own patched version of kubeadm in affected versions.
Contents of the patch (against kubernetes/kubernetes v1.20.4 tag):
```
diff --git a/cmd/kubeadm/app/phases/etcd/local.go b/cmd/kubeadm/app/phases/etcd/local.go
index 1965e916eed..8e94d0abe27 100644
--- a/cmd/kubeadm/app/phases/etcd/local.go
+++ b/cmd/kubeadm/app/phases/etcd/local.go
@@ -66,6 +66,10 @@ func CreateLocalEtcdStaticPodManifestFile(manifestDir, patchesDir string, nodeNa
spec = *patchedSpec
}
+	//Hack: Add a delay of 30 seconds
+	fmt.Printf("[etcd - metal3hack] Delay …
```
=> Download patched kubeadm binary for etcd startup bug in k8s v1.20.4

CODEOWNERS, renovate.json
This PR allows the Renovate bot to assign people to review its PR.
=> Renovate bot will automatically assign two people to review a PR

ci/images/userdata.tpl
Prevents Network Manager from adding nameserver entries in /etc/resolv.conf
=> Make /etc/resolv.conf immutable

ci/images/gen_metal3_centos_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh
While running centos integration tests with stream image, minikube is failing to start properly kvm and fails. i.e:
```
+ sudo su -l -c 'minikube start --insecure-registry 192.168.111.1:5000' centos
* minikube v1.20.0 on Centos 8 (kvm/amd64)
* Using the kvm2 driver based on user configuration
X Exiting due to PROVIDER_KVM2_ERROR: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to get emulator capabilities
error: internal error: unknown feature amd-sev-es
exit status 1
* Suggestion: Follow your Linux distribution instructions for configuring KVM
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/
make: *** [Makefile:4: install_requirements] Error 69
```
To fix or workaround it, simply creating an **empty** file in provisioning centos image script …
=> Move to CentOS stream

ci/images/gen_metal3_centos_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh, ci/scripts/image_scripts/provision_node_image_centos.sh
This PR modifies the scripts which are used to build **metal3 centos images** and **centos node images** to be able to drop usage of CentOS 8.3 image in both scripts and replace it with CentOS Stream image. 
As a consequence these are the modifications:
- Image hash pointing to CentOS8.3 located in CityCloud changed to CentOS8 Stream image hash in metal3 centos image generating script. 
- While running centos integration tests with stream image, minikube is failing to start properly kvm and fails. i.e:
```
+ sudo su -l -c 'minikube start --insecure-registry 192.168.111.1:5000' centos
* minikube v1.20.0 on Centos 8 (kvm/amd64)
* Using the kvm2 driver based on user configuration
X Exiting due to PROVIDER_KVM2_ERROR: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to get …
```
=> ✨ Drop CentOS8.3 and move to CentOS Stream

capo/README.md, capo/configure.sh
Due to continuous changes on the CAPI side, some times, the CAPO development environment breaks.
This PR fixes the CAPI version a know working version.
=> Fix CAPI to known working version with CAPO

ci/scripts/image_scripts/target_cluster_container_images.sh
Calico has released new images 3.20.0 but the latest manifest they have is still referencing to 3.191. We have pre-downloaded 3.20.0 images because they are available but in metal3-dev-env we are using the latest calico yaml which is pointing to 3.19.1 images.
=> Revert calico images to v3.19.1

ci/scripts/image_scripts/start_centos_ipa_build.sh
We have two vars not defined in IPA building scripts, causing the CI to fail.
```
Masking supported pattern matches of $RT_USER or $RT_TOKEN
[Pipeline] {
[Pipeline] sh
+ make build_ipa
/home/****/slave_root/workspace/airship_openstack_ipa_image_building/ci/scripts/image_scripts/start_centos_ipa_build.sh
/home/****/slave_root/workspace/airship_openstack_ipa_image_building/ci/scripts/image_scripts/start_centos_ipa_build.sh: line 20: CI_EXT_NET: unbound variable
/home/****/slave_root/workspace/airship_openstack_ipa_image_building/ci/scripts/image_scripts/start_centos_ipa_build.sh: line 23: IMAGE_NAME: unbound variable
No Port found for ci-builder-vm-20210821120027-int-port
Waiting for the host ci-builder-vm-20210821120027 to come up …
```
=> Fix unbound vars in IPA building

ci/jobs/artifactory_cleanup.pipeline, ci/scripts/artifactory/utils.sh, ci/scripts/image_scripts/artifactory_cleanup.sh
This commit adds a Artifactory directory cleanup logic to
ci/scripts/artifactory/utils.sh. The general purpose cleanup logic
supports artifact pinning (exclusion from cleanup), dry-run and
artifact retention functionalities.
This commit also creates a pipeline script and related shell scripts
to provide logic for a job to clean any artifact directory.
At the moment the cleanup pipeline only check centos stream based
IPA build artifacts but that can be extended by adding additional
Artifactory urls to the script.
=> Add build artifact cleanup logic to pipeline

ci/scripts/image_scripts/artifactory_cleanup.sh
Environment variables that contained the paths to the pinned artifact
lists had incorrect default values.
=> Fix incorrect default path of pinned artifacts

ci/scripts/image_scripts/provision_metal3_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh, ci/scripts/image_scripts/provision_node_image.sh, ci/scripts/image_scripts/provision_node_image_centos.sh
Node image image building jobs started to fail with CONTAINER_RUNTIME var being unbound.
This patch cleans up unnecessary listing of images and defaults  CONTAINER_RUNTIME to docker&podman for Ubuntu & CentOS respectively.
Example of failed CI job: https://jenkins.nordix.org/job/airship_openstack_node_image_building/95/consoleFull
=> Fix unbound var in node image building process

ci/scripts/image_scripts/provision_metal3_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh, ci/scripts/image_scripts/setup_monitoring_centos.sh, ci/scripts/image_scripts/setup_monitoring_ubuntu.sh
Add and configure the atop and sar monitoring tools to images. The tools are configured to run every minute and keep history for 3 days.
atop gives per process CPU, memory, disk and network statistics, while sar will give us overall system level stats.
I estimate for a 6 hour run, the tools will consume about 30 MB of disk space.
=> Add atop and sar monitoring tools to images

ci/scripts/image_scripts/source_cluster_container_images.sh
Since capm3 v1a4 tests can only survive with k8s < v1.22 we also need to prepull kind docker  image version 1.21.2
=> Add kind image v1.21.2 for v1a4 tests

ci/jobs/openstack_image_building.pipeline, ci/jobs/openstack_node_image_building.pipeline
Add `KUBERNETES_VERSION` var in image building pipeline so that value is inherited from JJB.
Please **DON"T MERGE** until https://gerrit.nordix.org/c/infra/cicd/+/10487 hasn't landed.
=> Add KUBERNETES_VERSION var in image building pipeline

ci/jobs/openstack_image_building.pipeline
We have added `KIND_NODE_IMAGE_VERSION` to our JJB so that we can manipulate the value while triggering the job. However, this var's value is not inherited in the next scripts because we haven't added it in our jenkins pipeline to fetch it from JJB.
=> Inherit KIND_NODE_IMAGE_VERSION value from JJB

ci/images/gen_metal3_centos_volume.sh, ci/images/gen_metal3_ubuntu_volume.sh, ci/scripts/image_scripts/provision_metal3_image.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh
The CentOS images currently don't have the 01 script run in them. This means that Docker images are pulled unnecessarily and the build time is prolonged. This is because of a missing 'true' argument when the provisioning script is run.
Previously, cloning metal3 and running the 01 script was gated in the image building process by a variable called DEPLOY_METAL3, which took the first argument the script was run with as a boolean. The provisioning scripts explicitly state that they deploy metal3, so I can't see a purpose for this variable and have removed it to ensure that we consistently run the 01 script from metal3 in our images.
=> Always run 01 script in image building process

ci/scripts/image_scripts/provision_metal3_image_centos.sh
This is required by the python3-bcrypt and python3-passlib packages now that we trigger the 01 script in the image building process.
=> Install EPEL in centos

ci/images/gen_base_ubuntu_image.sh, ci/images/gen_metal3_centos_image.sh, ci/jobs/openstack_image_building.pipeline
This PR updates the image build scripts to include name instead of id as source image since the id's are different in different region for the same source image. Also, a base image creation is needed for Frankfurt region since metal3 Ubuntu image sources it.
=> Update image build scripts

ci/jobs/openstack_image_building.pipeline
Previously, the image build timeout was set to 60 minutes. However, this isn't enough for the CentOS image build in the Kna1 region to reliably finish, so let's bump it to 90 minutes.
=> Increase image build timeouts to 90 minutes

scripts/update-nordix-repos-master.sh
This commit also makes the sync script shellcheck compatible.
=> Fix syncing for capm3 release branches

ci/jobs/airship_integration_tests.pipeline
https://github.com/metal3-io/project-infra is using main as the default branch. So, 
updating reference here as well.
=> Rename project-infra repo branch reference to main from master

ci/jobs/airship_integration_tests.pipeline
we need to pass KUBERNETES_VERSION variable when we want to check uplifting of k8s  version with airship integration tests. 
By adding it to vars.sh file we pass KUBERNETES_VERSION to metal3-dev-env
=> Pass k8s version variable for airship integration tests

ci/scripts/image_scripts/build_ipa.sh, ci/scripts/image_scripts/ipa_builder_elements/ipa-module-autoload/install.d/80-ipa-module-autoload, ci/scripts/image_scripts/start_centos_ipa_ironic_build.sh
At the time of writing DIB has an element only for blacklisting
kernel drivers, and in order to support PERC11 sas controllers
the megaraid_sas kernel module is needed in IPA thus a custom
element was created to add support for configuring kernel module
loading during IPA boot.
=> add ipa element that configures kernel modules

ci/images/centos_userdata.tpl, ci/images/ubuntu_userdata.tpl
This adds a metal3ci user to image userdata. The airshipci user will still be created and used by the scripts. This additional user will let us swap over to using the metal3ci user once images have been built with both users.
=> Add metal3ci user to image userdata

ci/jobs/metal3_dev_tools_integration_tests.pipeline
This PR adds passing KUBERNETES_VERSION to node image building stage of airship dev tools integration tests, so temporary images are being built with correct k8s version.
=> Pass KUBERNETES_VERSION value to image building stage of metal3 dev tools integration tests

ci/jobs/openstack_node_image_building.pipeline
This PR adds post section in node_image_building pipeline, which triggers image_building job after its successful run
=> Trigger image building job after node image building job

ci/jobs/artifactory_cleanup.pipeline, ci/scripts/harbor/harbor_utils.sh, ci/scripts/image_scripts/artifact_cleanup.sh, ci/scripts/image_scripts/run_build_ironic.sh, ci/scripts/image_scripts/start_centos_ipa_ironic_build.sh
This commit:
Implements a general purpose harbor bash library.
Implements the cleanup process for harbor.
Moves the harbor cleanup process to the same script where the artifactory
cleanup process is handled and renames the file from artifactory_cleanup.sh to
artifact_cleanup.sh.
By using the aforementioned bash library implements a process to
save the digest of the ironic-image container image that is being
built during the IPA build process and saves the digest to the metadata file.
=> Implement automated Harbor cleanup process

scripts/update-nordix-repos-master.sh
I noticed that we don't have all releases in the Nordix fork of CAPI. For example, there is no tag v1.1.2 in the fork. This should fix it I think.
=> Sync release branches for CAPI

ci/jobs/metal3_dev_tools_integration_tests.pipeline
This PR we are setting default KUBERNETES_VERSION value  in metal dev tools interation tests pipeline
=> Fix passing k8s version to metal3 dev tools integration test pipeline

ci/scripts/image_scripts/provision_metal3_image_centos.sh
Also switched yum to dnf (we already used dnf in one place and yum is
linked to dnf).
We got the following error when building the centos image:
```
Error:
Problem: package centos-stream-repos-8-4.el8.noarch requires centos-gpg-keys = 1:8-4.el8, but none of the providers can be installed
- cannot install both centos-gpg-keys-1:8-5.el8.noarch and centos-gpg-keys-1:8-4.el8.noarch
- cannot install the best update candidate for package centos-stream-repos-8-2.el8.noarch
- cannot install the best update candidate for package centos-gpg-keys-1:8-2.el8.noarch
```
According to [this](https://linux-community.web.cern.ch/t/centos8-dnf-update-fails-any-suggestion/120), using `distro-sync` should solve the dependency issue.
=> Use distro-sync instead of update on centos

ci/jobs/metal3_dev_tools_integration_tests.pipeline, ci/jobs/openstack_image_building.pipeline
Integration tests and image building pipelines are already using colored output, which makes the logs hard to read without this.
=> Enable colored output for pipelines that use color

ci/images/centos_userdata.tpl, ci/scripts/image_scripts/provision_metal3_image_centos.sh
resolv.conf was previously made immutable to prevent NetworkManager
and/or cloud-init from modifying it. This was causing issues with
cloud-init, since it still tried to modify it.
Most of the time things worked ok (except that cloud-init had error
status). But every now and then this error seemed to cause other issues.
E.g. the resizing of the filesystem or injection of authorized
ssh keys failed.
This commit properly configures NetworkManager to set the nameservers
and cloud-init to avoid touching resolv.conf.
=> Fix cloud-init error on centos

ci/scripts/image_scripts/configure_nameservers_centos.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh, ci/scripts/image_scripts/provision_node_image_centos.sh
I totally missed that the node images didn't use the same script when I changed the cloud init. This should fix it.
The reason I didn't add these commands in the user-data, is that cloud-init itself is making network modifications, like disabling NetworkManager DNS. So instead of hoping that it goes in the correct order I think it is better like this.
=> Fix nameservers on centos node images

ci/images/README.md, ci/images/gen_base_ubuntu_image.sh, ci/images/gen_jumphost_jenkins_ubuntu_image.sh, ci/images/gen_metal3_centos_image.sh, ci/images/gen_metal3_ubuntu_image.sh, ci/images/image_builder_template.json, ci/images/run_local.sh
- Use source image name directly instead of searching for the ID based on the name.
- Remove hard coded source image
- Parameterize ssh_keypair_name and reuse_ips
- Provide overridable defaults for local script
- Don't upload locally built images to artifactory
=> Update script for building metal3 images locally

ci/images/gen_node_ubuntu_image.sh, ci/images/image_builder_template_node.json
I missed updating the node template when I updated the metal3 template. This should fix the CentOS node image building pipeline.
=> Fix packer template for node building

ci/scripts/image_scripts/target_cluster_container_images.sh
Control-plane, etcd, kube-proxy and coredns can be pre-pulled to speed
up node provisioning and minimize network traffic.
This adds some unnecessary images for non-control-plane nodes. If this
is a concern, we could consider using separate images for workers and
control-plane nodes.
=> Pre-pull more container images in node image

ci/scripts/image_scripts/provision_base_image.sh, ci/scripts/image_scripts/provision_node_image.sh, ci/scripts/image_scripts/setup_docker_ubuntu.sh
- sudo apt-get upgrade -f -y restarts the services and image building hangs so modifying needrestart  
-  docker-ce docker-ce-cli doesnt have the recommended version anymore for 22.04 so installing the latest. 
Co-authored-by: Lennart Jern lennart.jern@est.tech
=> Modify base image and docker installation scripts to accommodate Ubuntu 22.04 image building

ci/scripts/image_scripts/build_ipa.sh
There was a missmatch between the "oslo-log" dependency required by
IPA and opendev.org/openstack/requirements/src/branch/master/upper-constraints.txt.
=> Add workaround to solve the oslo-log issue

ci/scripts/image_scripts/build_ipa.sh, ci/scripts/image_scripts/ipa_builder_elements/ipa-add-buildinfo/install.d/80-ipa-add-buildinfo
This change was needed because centos 8 stream is slowly loosing upstream support and
the systemd packaged with centos 8 stream had a bug that affected udev thus the inspection
and provisioning process of Ironic.
This change also contains a additional element that puts a buildinfo file into IPA to
help with future debugging tasks.
=> Uplift IPA base image to centos 9 stream

ci/images/centos_userdata.tpl, ci/images/ubuntu_userdata.tpl, ci/scripts/image_scripts/provision_base_image.sh, ci/scripts/image_scripts/provision_node_image.sh
The new ssh key uses the ed25519 format which is more secure, should
give better performance and avoid some issues with newer OSes that are
disabling some RSA hashes.
I also included a couple of small changes to make the image build go through:
- Configure needsrestart to only print kernel hints (it was hanging waiting for user input)
- Run apt-get update after apt-get dist-upgrade. This seems to be necessary or else it cannot find the packages it is trying to install.
- Use apt-get instead of apt in more places (there are warnings about using apt in scripts).
I can move these small fixes to a separate PR if required. In that case we will need to merge it before this as I was unable to build the image without them.
=> Add new ssh key for the CI and adding apt-get instead of apt

ci/images/centos_userdata.tpl, ci/images/ubuntu_userdata.tpl
kvm tdp_mmu was enabled by default in the new kernels and started causing kernel crush in both centos and ubuntu. This PR disable it to fix this issue.
https://lore.kernel.org/lkml/20210726163106.1433600-1-pbonzini@redhat.com/
=> Disable kvm tdp_mmu to fix kernel crush issue

ci/images/gen_metal3_centos_image.sh
Parallel node image building is failing because of the same key name for Ubuntu and CentOS. This PR will change the key name for CentOS node image builiding.
=> Change key name for CentOS for parallel node image building

ci/images/image_builder_template.json
Curenntly image building is failing with no space issue. This PR will increase the disk size to tackle that problem.
=> Increase flavor disk size to 50GB

ci/scripts/image_scripts/install_crio_on_ubuntu.sh
This is not really needed in the CI where we always use the same image to start from. But it is useful if you want to manually build images using both Ubuntu 20.04 and 22.04.
=> Use correct repository for cri-o depending on OS version

ci/images/gen_base_ubuntu_image.sh
There were  some repository update issues during baseimage building
with ubuntu 22 so it needed to be downgraded.
=> downgrade Ubuntu version in image building

resources/docker/workspace/Dockerfile
Ubuntu 20.04 is used everywhere else in the repository thus it has
been decided that this should be aligned too.
=> align container image base with other images

ci/scripts/image_scripts/provision_metal3_image_centos.sh
Openstack image building [job](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_openstack_image_building/312/execution/node/103/log/) failing to build metal3 centos image with the following
```
[0;32m    openstack: + sudo podman pod create -n ironic-pod[0m
[0;32m    openstack: Error: building local pause image: finding pause binary: exec: "catatonit": executable file not found in $PATH[0m
[0;32m    openstack: make: *** [Makefile:4: install_requirements] Error 125[0m
[1;32m==> openstack: Provisioning step had errors: Running the cleanup provisioner, if present...[0m
```
error. This should fix the missing package issue and survive the tests later on.
=> Install missing catatonit package

ci/jobs/metal3_dev_tools_integration_tests.pipeline
Fix for project-infra part is [here](https://github.com/metal3-io/project-infra/pull/428)
This PR fixes receiving IMAGE_NAME and IMAGE LOCATION variables from pipeline for metal3 dev tools integration tests. Metal3 dev tools integration tests are not using temporarily built node image, but default node image. Cause of the problem is IMAGE_NAME and iMAGE_LOCATION variables are not passed to the tests properly. This issue started appearing after we randomized the vars.sh file name [here](https://github.com/metal3-io/project-infra/blob/ef01400cb9c069290865fa01bd7e08b218c84499/jenkins/scripts/integration_test.sh#L129)
=> Rename var.sh to devtoolsvars.sh for dev tools integration tests

ci/scripts/image_scripts/configure_nameservers_centos.sh, ci/scripts/image_scripts/configure_network_centos.sh, ci/scripts/image_scripts/provision_metal3_image_centos.sh, ci/scripts/image_scripts/provision_node_image_centos.sh
This PR solves issue of two connection profiles competing for eth0 interface. We set lower priority to System-eth0.nmconnection profile. 
The dev-env part of the solution is [here](https://github.com/metal3-io/metal3-dev-env/pull/1062)
=> Change node image network config to keyfile format in centos

ci/scripts/image_scripts/provision_metal3_image_centos.sh
- Don't install podman-catatonit. It is pulled in as a dependency to
podman and when we explicitly install it we get conflicts with the
catatonit package.
- Use the Nordix pull through cache for container images.
- Remove some unnecessary commands:
- podman was installed twice
- curl and nss were updated right after updating all packages
- one more update before installing the EPEL repo
=> Fix package conflict

Makefile, wow/fullstack-build.md
This commit does two things.
1. Aligns the old IPA-IRONIC build documentation with the logic of the fullstack job.
2. Fixes a typo in the Makefile that blocked the fullstack build process.
=> Introduce fullstack build documentation

ci/images/centos_userdata.tpl
A workaround to the issue of losing ssh connection after creating a bridge
=> 🐛 Exclude NetworkManager upgrades

ci/jobs/openstack_image_building.pipeline
This mount was mistakenly removed in a previous commit, which is causing issue now
=> ci:Add METAL3_CI_USER_KEY mount back to image building docker

ci/jobs/openstack_image_building.pipeline
The mounts seem to be needed at all times.
=> CI: Add METAL3_CI_USER_KEY mount in all builds

ci/jobs/openstack_image_building.pipeline
The mount syntax was wrong, which made mounting fail and the cred missing inside the docker containers.
=> CI: Fix mount syntax in build image job

ci/scripts/image_scripts/bmh-patch-long-serial.yaml, ci/scripts/image_scripts/build_ipa.sh, ci/scripts/image_scripts/start_centos_fullstack_build.sh
As https://review.opendev.org/c/openstack/ironic-python-agent/+/855866 
has been merged there is no need to use the custom fix from the Nordix branch.
This change also adds:
- customization options for running the full-stack build outside of the Metal3 CI
- customization options for adding and configuring user for IPA
=> Build IPA based on opendev upstream repository

ci/images/gen_metal3_ubuntu_image.sh, ci/jobs/openstack_node_image_building.pipeline
Last commit had a small syntax error, which made the pipeline failed.
=> CI: Fix minor issue in node building pipeline

ci/images/README.md, ci/scripts/image_scripts/configure_network_ubuntu.sh, ci/scripts/image_scripts/provision_metal3_image_ubuntu.sh
Testing cloudflare DNS here. On centos we use google. Any of them should be better than the uncertainty and unreliability due to the DHCP added nameservers in openstack.
Also updated docs to explain how to create an openstack keypair.
=> Configure nameservers for the metal3 ubuntu image

ci/jobs/linter_tests.pipeline, ci/scripts/image_scripts/build_ipa.sh, ci/scripts/image_scripts/provision_jumphost_jenkins_base_img.sh, ci/scripts/image_scripts/provision_metal3_image_ubuntu.sh, ci/scripts/image_scripts/run_build_ironic.sh, ci/scripts/image_scripts/setup_chrony_ubuntu.sh, ci/scripts/image_scripts/setup_qemu_ubuntu.sh, scripts/run_metal3_vm.sh, tools/setup_machines/providers/kinder/setup_test_environment.sh
Apt does not have stable CLI, and gives out warnings when used from script context. Replace apt with apt-get.
=> Use apt-get instead of apt in scripts

ci/scripts/image_scripts/build_ipa.sh, ci/scripts/image_scripts/ipa_builder_elements/ipa-cleanup-dracut/cleanup.d/99-ipa-cleanup-dracut
The IPA image size has grown to more than 800mb which limits the requirement for the image size.  It seems that there are three dracut.* directories present in the image which has 181Mb size each. So adding this directory cleanup element in our IPA building image.
=> Add element in IPA finalise stage to cleanup dracut*

Makefile
Upgrade shellcheck from v0.7.0 to v0.9.0 and pin by digest. This way it is the same as all the other repos, and pinned.
Note: there are 100+ complaints from shellcheck, even on 0.7.0, those will be fixed in another commit on a later date.
=> makefile: pin shellcheck to v0.9.0

ci/scripts/image_scripts/provision_node_image_centos.sh
Current Centos9 version we are using have an issue with bnx2x firmware. It is blocking NIC from coming up in BML tests. This PR fixes the issue
=> Fixes bnx2x firmware issue with NIC

ci/scripts/image_scripts/provision_node_image_centos.sh
In v1.41.7 version of NM is not showing a failure when creating a bridge
=> Remove downgrading NetworkManager for Centos node image

ci/scripts/image_scripts/build_ipa.sh, ci/scripts/image_scripts/ipa_builder_elements/override-simple-init/environment.d/99-override-simple-init, ci/scripts/image_scripts/ipa_builder_elements/override-simple-init/post-install.d/99-override-simple-init, ci/scripts/image_scripts/ipa_builder_elements/override-simple-init/post-install.d/glean-early-override-template.service
This commit is the part of a series of commits
that introduces new features to the IPA image in order to support various dhcpless use-cases.
This commit introduces the following:
- simple-init element using modified glean from fork
- simple-init now supports custom block device label when looking for the network_info.json
=> add support for custom config-drive in IPA part 1

ci/images/README.md, ci/images/centos_userdata.tpl, ci/images/run_local.sh, ci/images/ubuntu_userdata.tpl, ci/scripts/openstack/utils.sh
- fix failing parameter expension of the container env vars (this was caused by shellcheck related refactoring)
- remove unnecessary container env vars
- add timestamp to the generated image otherwise in case of
subsequent image builds the openstack client won't be abel to distinguish between the images and won't save the new image
- introduce more explicit variable nameing in certain cases
- remove key_pair variable from the packer vars as it is not needed and just complicates the script
- restrict openstack related logic into the container, so nothing that talks to openstack will be executed outside the container thus there is no need to have the ostack client installed on the host system
- add sandbox mode, in case the user would like to look around in ostack without building an image …
=> fix run_local image builder script

resources/docker/builder/Dockerfile
openstack plugin is not bundled with packer by default anymore, adding it explicitly
=> Adding openstack plugin to packer

ci/jobs/metal3_dev_tools_integration_tests.pipeline
This switches the dev-tools integration test pipeline to use dynamic jenkins workers instead of the old static workers that we have used so far. The idea is to ensure that the dynamic workers can be used without risking too much.
=> Switch dev-tools integration pipeline to use dynamic workers

ci/jobs/openstack_node_image_building.pipeline, ci/scripts/image_scripts/backup_node_images.sh
This PR adds a post condition in node image build pipeline, where after successful build newly built node image is pushed to artifactory for backup. Also adds a script to keep five latest backup images.  
Name format of backup node image:    IMAGE_OS_VERSION_ID_NODE_IMAGE_K8S_KUBERNETES_VERSION_DATE_COMMITHASH
Example:
CENTOS_9_NODE_IMAGE_K8S_v1.27.1_20230607T1319Z_22101ef.qcow2
=> Backup node images

ci/jobs/openstack_image_building.pipeline, ci/scripts/image_scripts/share_image.sh, ci/scripts/openstack/utils.sh
As KEEP tests are planned to run in dev2 project, metal3 images must be available in dev2.
This PR adds post condition to pipeline, after each successful built images will be shared to dev2 project.
Related to [this](https://github.com/metal3-io/project-infra/pull/563).
=> Share metal3 image to dev2 project after successful build

ci/scripts/image_scripts/build_ipa.sh
Custom IPA source wasn't used druing building, IPA source was collected from upstream. (This change does not affect the element usage)
This commit:
- Fixes the path variable that specifies the location of the IPA source code.
- Added automatic work directory cleaning to IPA build script to speed up local building (provides benefit when not used in CI)
=> correct IPA source path used during building

ci/scripts/image_scripts/provision_jumphost_jenkins_base_img.sh
This adds libvirt and related tools to the Jenkins (and jumphost) images. Libvirt is needed to be able to run BMO e2e tests where we use VMs as BMHs.
I have tested this by building an image manually and then switching the dynamic Jenkins workers to use it. Here is a test run: https://jenkins.nordix.org/job/metal3-bmo-e2e/22/
=> Add libvirt to Jenkins images

ci/images/gen_metal3_centos_image.sh, ci/scripts/image_scripts/provision_node_image_centos.sh, ci/scripts/image_scripts/provision_node_image_ubuntu.sh
This commit:
- Changes "mv" commands to "cp" in order to avoid failures in case of packer "retry" actions
- Also upgrades the Centos 9 Stream source image as the previous version was a year old.
=> align node image building with packer "retry" workflow

Makefile, ci/jobs/container_image_building.pipeline, scripts/build-container-image.sh
Additionally, use env vars in build script to make it easier to integrate the script with Jenkins. Also rearranged make targets alphabetically.
=> Add ci pipeline to build container images

ci/scripts/image_scripts/install_crio_on_centos.sh, ci/scripts/image_scripts/provision_node_image_centos.sh
crictl is already put in place /usr/local/bin [here](https://github.com/Nordix/metal3-dev-tools/blob/main/ci/scripts/image_scripts/install_crio_on_centos.sh#L34) in the install_crio_on_centos.sh script called a line before. Instead of putting it to /usr/bin in the provision_ script, we now put it in /usr/bin right away.
=> Remove unnecessary copy of crictl binary

resources/docker/builder/Dockerfile
Pin builder and linter Docker images with SHA digest, so they don't change unless explicitly changed.
=> pin builder and linter Docker images

scripts/update-nordix-repos-master.sh
Remove 0.5 branch to balance it out. CAPO maintainers do not publish patch releases really, but keeping some as its lightweight op.
=> add capo release-0.9 branch for syncing

resources/docker/builder/Dockerfile
Downgrade Packer to 1.9.2, the last version from BUSL was taken into use. Eventually Packer will be replaced completely.
=> downgrade packer to 1.9.2

.markdownlint-cli2.yaml, README.md, ci/images/README.md, ci/scripts/openstack/README.md, getting-started.md, hack/markdownlint.sh, tools/scalability/README.md, tools/setup_machines/README.md, wow/Upgrade-image.md, wow/citycloud.md, wow/fullstack-build.md, wow/github-workflow.md, wow/jenkins_ci/README.md
Also fix or locally ignore markdownlint issues.
- project-infra PR https://github.com/metal3-io/project-infra/pull/619 needs to merge for markdownlint here to pass
=> switch markdownlint container to markdownlint-cli2

ci/scripts/openstack/id_ed25519_metal3ci.pub
This is part of the CI key rotation. We are replacing the old ssh key with the new one.
Signed-off-by: Kashif Khan <kashif.khan@est.tech>
=> Replace the old ssh key with a new one

ci/jobs/update_nordix_repos.pipeline
This PR set new jenkins worker label metal3ci-8c16gb to nordix repo update job as we are not using  metal3ci-4c16gb label anymore
=> Set new jenkins worker label to nordix repo update job

scripts/update-nordix-repos-master.sh
This PR adds release-1.8 branch to the list of branches we need to sync from upstream.
/hold
=> :seedling: Add release 1.8

scripts/update-nordix-repos-master.sh
As we accidentally published BMO v0.8.0-rc.0 instead of v0.7.0-rc.0, we decided to skip release-0.7 and jump directly to release-0.8.
=> :seedling: Change BMO release-0.7 branch to release-0.8 branch

ci/jobs/artifact_cleanup.pipeline, ci/jobs/container_image_building.pipeline
Change worker label to commonly used one metal3ci-8c16gb-ubuntu
also fixes label for container image  building.
=> Change worker label

scripts/update-nordix-repos-master.sh
Add CAPI 1.9, CAPO 0.11 and ironic-image 27.0 release branches to be synced.
=> update synced branches for CAPI, CAPO and ironic-image

OWNERS_ALIASES
@mquhuy is not active as an approver in Nordix repos anymore. Thanks Huy for all your contributions.
Signed-off-by: Kashif Khan <kashif.khan@est.tech>
=> Remove @mquhuy from approvers

ci/jobs/artifact_cleanup.pipeline
The ssh key and openstack variables are remnants from before the dynamic jenkins workers and no longer needed.
=> Cleanup artifact cleanup pipeline
